# Generated by Django 4.2.16 on 2026-05-02 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10)),
                ('path', models.CharField(help_text='/users, /health', max_length=255)),
                ('sla_latency_ms', models.PositiveIntegerField(default=500, help_text='Max acceptable latency (ms)')),
                ('sla_error_rate', models.FloatField(default=0.05, help_text='Max error rate (e.g. 0.05 = 5%)')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(help_text='Base URL, e.g. https://api.example.com')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('response_time_ms', models.FloatField()),
                ('status_code', models.IntegerField()),
                ('is_error', models.BooleanField()),
                ('sla_breached', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.endpoint')),
            ],
        ),
        migrations.AddField(
            model_name='endpoint',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.project'),
        ),
        migrations.AlterUniqueTogether(
            name='endpoint',
            unique_together={('project', 'method', 'path')},
        ),
    ]
