# Generated by Django 4.2.16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_minutes', models.CharField(choices=[('1', 'Each minute'), ('5', 'Every 5 minutes'), ('10', 'Every 10 minutes'), ('15', 'Every 15 minutes'), ('30', 'Every 30 minutes'), ('60', 'Every hour'), ('360', 'Every 6 hours'), ('1440', 'Every day')], default='5', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='monitor.project')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('sla_breach', 'SLA Breach'), ('endpoint_down', 'Endpoint Down'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.endpoint')),
                ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.measurement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='monitor_ale_project_b80544_idx'), models.Index(fields=['alert_type', 'created_at'], name='monitor_ale_alert_t_6bbacf_idx')],
            },
        ),
    ]
