# Generated by Django 4.2.16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for identification', max_length=100)),
                ('webhook_type', models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord'), ('generic', 'Generic Webhook')], max_length=20)),
                ('webhook_url', models.URLField(help_text='Webhook URL (Slack, Discord, or custom)')),
                ('trigger_type', models.CharField(choices=[('sla_breach', 'SLA Breach'), ('endpoint_down', 'Endpoint Down'), ('all_errors', 'All Errors')], default='sla_breach', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.project')),
            ],
            options={
                'unique_together': {('project', 'webhook_url')},
            },
        ),
    ]
