# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_webhook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='webhook_type',
        ),
        migrations.AlterField(
            model_name='webhook',
            name='webhook_url',
            field=models.URLField(help_text='Webhook URL for notifications'),
        ),
    ]
